profile: dev

grpcserver:
  port: 50052
  name: RDB_Reader
  timeout: 5
  mode: debug  
  path: api/gitreader/v1


rdb:
  host: 127.0.0.1
  database: TestRepository
  username: xqledger
  password: toor
  poolsize: 2
  timeout: 30

