profile: default

grpcserver:
  port: 50052
  name: RDB_Reader
  timeout: 5
  mode: debug  
  path: api/rdboperator/v1


rdb:
  host: "rdb"
  database: "TestRepository"
  username: "xqledger"
  password: "toor"
  poolsize: 5
  timeout: 60